# Application environment
environment: development  # Change to 'production' for production environment

# Database configuration
db:
  path: data/database.db

# Language settings
languages:
  supported: [en, es]
  default: en

# Distance settings
distance:
  max_threshold: 10.0
  min_value: 0.0
  unit: mile

# Time settings
time:
  periods: [morning, afternoon, evening, night]
  period_ranges:
    morning:
      start: "06:00"
      end: "11:59"
    afternoon:
      start: "12:00"
      end: "16:59"
    evening:
      start: "17:00"
      end: "20:59"
    night:
      start: "21:00"
      end: "23:59"
  days_ahead: 7
  format:
    date: "%b %d"
    time: "%H:%M"

# Logging
log_level: INFO

# User preferences configuration
user_preferences:
  # Keys used in the application
  keys:
    language: 'language'
    food_requirements: 'food_requirements'
    max_distance: 'max_distance'
    time_slots: 'time_slots'
    address: 'address'
    pickup_datetime: 'pickup_datetime'
  
  # Questions for interactive mode
  questions:
    language: "Which language would you prefer to use? (en/es): "
    food_requirements: "What are your food requirements? (e.g., halal, kosher, vegetarian): "
    distance: "What is the maximum distance you can travel to get food? (in miles): "
    time_slots: "Please select your preferred pickup time from the available slots:"
    location: "Please enter your full address (country, city, street, zip code): "
  
  # Validation rules
  validation:
    language:
      valid_options: ['en', 'es']
  
  # Default values for development mode
  defaults:
    language: 'en'
    food_requirements: 'vegetarian'
    max_distance: 6
    time_slots: [
      "Mar 25 afternoon",
      "Mar 25 evening",
      "Mar 25 night",
      "Mar 26 morning",
      "Mar 27 afternoon",
      "Mar 30 evening",
      "Apr 1 morning",
      "Apr 1 afternoon"
    ]
    address: '5702 Vassar Drive, College Park, Maryland, 20740' 