# config/config.yaml - Unified configuration template

# ... other sections remain unchanged ...

# -------------------------------
# User Preferences Configuration
# This section is used for interactive user prompts.
# -------------------------------
user_preferences:
  keys:
    language: language
    address: address
    pickup_day: pickup_day
    pickup_time: pickup_time
    transportation: transportation
    health_dietary: health_dietary
    religious_dietary: religious_dietary
    kitchen_access: kitchen_access
    services: services
    proxy_pickup: proxy_pickup
    max_distance: max_distance

  questions:
    language: "Which language would you prefer to use? (en/es): "
    address: "Please share your address or location: "
    pickup_day: "Would you like to get food today or another day this week? (today/tomorrow/this_week): "
    pickup_time: "Please select your preferred pickup time from the available slots:"
    transportation: "Are you able to travel to a food pantry using a private vehicle or public transit? (yes/no): "
    health_dietary: "Do you have any dietary restrictions or diet-related illness? (Select one or multiple): "
    religious_dietary: "Do you have any dietary restrictions due to religious or cultural reasons? (Select one or multiple): "
    kitchen_access: "Do you have access to a kitchen to store and/or cook food? (Select one): "
    services: "Do you also need any of these other services? (Select all that apply): "
    proxy_pickup: "Can a relative or friend travel to a pantry for you? (yes/no): "
    max_distance: "What is the maximum distance you can travel to get food? (in miles): "

  valid_options:
    language: ["en", "es"]  # , "zh", "ar", "vi", "am"
    pickup_day: ["today", "tomorrow", "this_week"]
    transportation: ["yes", "no"]
    health_dietary:
      - "Diabetic Meal"
      - "Low Sodium / Hypertension Meal"
      - "Low Sugar Meal"
      - "Low Fat / Cardiac Meal"
      - "Renal/Kidney-Friendly Meal"
      - "Gluten-Free/Intolerant Meal"
      - "All-Produce/Fruit & Vegetable Meal"
      - "Dietary/Pathological Meal"
      - 
        option: "Allergic to"
        follow_up:
          - "Please specify what food you are allergic to: "
    religious_dietary:
      - "Halal Meal"
      - "Kosher Meal"
      - "Hindu Meal"
      - "Non-Beef Meal"
      - "Non-Pork Meal"
      - "Vegetarian Meal"
      - "Vegetarian Lacto-Ovo Meal"
      - "Vegetarian Vegan Meal"
      - "Raw Vegetarian Meal"
      - "Vegetarian Indian Meal"
      - "Vegetarian Oriental Meal"
      - "Vegetarian Jain Meal"
    kitchen_access:
      - "Yes, so I can take raw food or tins"
      - "No, so I need Prepared meals"
    services:
      - "Housing"
      - "Government benefits"
      - "Financial assistance"
      - "Services for older adults"
      - "Behavioral health"
      - "Health care"
      - "Child care"
      - "English language classes"
      - "Job training"
    proxy_pickup: ["yes", "no"]
    max_distance: null

  defaults:
    language: "en"
    address: "5702 Vassar Drive, College Park, Maryland, 20740"
    pickup_day: null
    pickup_time: null
    transportation: null
    health_dietary: null
    religious_dietary: null
    kitchen_access: null
    services: null
    proxy_pickup: null
    max_distance: 6
