# Development environment configuration

# User preferences for testing
user_preferences:
  language: "en"
  food_requirements: "vegetarian"
  max_distance: 10
  time_slots: "morning"
  address: "5702 Vassar Drive, College Park, Maryland, 20740"

# Other development settings
environment: "development"
log_level: "INFO" 